### ISSUE TITLE
It is possible activate the triggers per interface

### ISSUE THREAD

**Issue by pedromendes96** [NickStrupat/EntityFramework.Triggers#34]
Hi,

I would like to know if it is possible to activate triggers for a kind of interface. I already tried this approach but without success.

For example:

```
public interface someInterface
{
      BeforeCreate();
}
```

```
public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken))
{
            Triggers<SomeInterface>.Updating += entry => entry.Entity...
            
            return this.SaveChangesWithTriggersAsync(base.SaveChangesAsync, acceptAllChangesOnSuccess: true, cancellationToken: cancellationToken);
}
```

**Comment by NickStrupat** [comment]
Hi there,

You are on the right track, but you only want to run your

`Triggers<SomeInterface>.Updating += entry => entry.Entity...`

code once.

Classes are a bit easier since you can put the trigger initialization in that class's static constructor. For interfaces... just have some initializer code that runs once to add the triggers handlers.
