### ISSUE TITLE
How to use with DDD

### ISSUE THREAD

**Issue by rafaelcustodio** [NickStrupat/EntityFramework.Triggers#8]
Hello,

Im using a ddd structure, in this case dont want to add more references in my Domain project.
We have a way to make a class ITriggerable from my data project?

Thank you

**Comment by NickStrupat** [comment]
Hi,

Yes, that is possible. Essentially, I made the empty `ITriggerable` interface so that the extension methods are available only to the intended entity classes. Otherwise, all classes could mistakenly have unusable triggers enabled for them. This restriction is merely a semantic one, not technical.

One potential solution is to remove that semantic restriction from `EntityFramework.Triggers`. This would allow you to enable triggers on your decoupled data models. I'm open to that, I'm just not 100% sure of its implications yet.

Another solution would be to, in the project where you are adding triggers, create a derived class for each of your data model classes. Something like this...

In the project containing your data models

``` csharp
// Your data model
public class Thing {
    // All of the properties
}
```

In the project where you want to add triggers

``` csharp
internal class ThingTriggerable : Thing, ITriggerable {
    static ThingTriggerable() {
        Triggers<ThingTriggerable>.Inserting += entry => { /* ... */ }
    }
}
```

You would also need to derive from your `DbContext` class.

**Comment by NickStrupat** [comment]
@rafaelcustodio FYI, the new version removed the `ITriggerable` interface entirely.
